### ISSUE TITLE
Cross-compiling T4C with Scala 3

### ISSUE THREAD

**Issue by catostrophe** [trace4cats/trace4cats#229]
Below is the list of issues to be resolved to make it compile with Scala 3.

**Comment by catostrophe** [comment]
- `better-monadic-for` plugin is not supported and will probably never be
- some libs are not published for Scala 3 at all and will probably never be - we should use their 2.13 versions in the dotty compat mode
- some libs are published for Scala 3, but not the latest version - we should wait for their releases rather than build with Scala 3.0.0-M2
- some code hygiene is needed
- more to be discovered

**Comment by ybasket** [comment]
Scala 3 final is out, so it would be cool if trace4cats started to cross-build. I can offer some help on that as well :)

Updates to the list above:
- log4cats, vulcan and fs2-kafka are published for Scala 3
- magnolia has a Scala 3 version that's slightly different from its discontinued Scala 2 predecessor => probably requires specific sources (or usage of shapeless-deriving on Scala 3)
- `better-monadic-for` won't have a Scala 3 version, but some of the syntax is available under `-source:future`
- builds with mixed 2.13 and 3.0 dependencies have proven too be fragile so far (esp if they depend on the same lib), so ideally no mix necessary

**Comment by catostrophe** [comment]
@ybasket 
`vulcan-generic`, `vulcan-enumeratum` are not published

I tried to migrate to `mangolia`, but the derived instances for tests didn't work well. So we'll stick to `kittens`, which should be released soon, since `shapless3` is out.

**Comment by catostrophe** [comment]
@ybasket feel free to make a PR if you can.
The problem is we use `enumeratum`. We can try to get rid of it. I don't think we use `findValues`. But we rely on some integrations and derivations.

It would be great to start releasing at least some of the modules.

**Comment by catostrophe** [comment]
Kittens migrated to Scala3/Shapeless3 and will be released soon

**Comment by ybasket** [comment]
@catostrophe Just opened https://github.com/janstenpickle/trace4cats/pull/534 for `enumeratum` and `better-monadic-for`.

I also experimented with just adding Scala 3 to the build (see my branch here: https://github.com/ybasket/trace4cats/tree/scala-3). Some modules compile just fine, so far the code itself seems relatively unproblematic. It's the dependencies that will cause headache, `vulcan-generic` and even worse, `circe-generic-extras`. 

`scalacheck-shapeless` doesn't seem to be used too much, just very few ugly manual instances and it wouldn't be necessary anymore (if someone adds `Mirror`-based derivation for `Arbitrary`, one could also easily cross-build using version-specific `trait`s stuffed with the instances).

**Comment by catostrophe** [comment]
> `scalacheck-shapeless` doesn't seem to be used too much

trait `ScalacheckShapeless` is injected almost everywhere in tests

**Comment by ybasket** [comment]
> trait ScalacheckShapeless is injected almost everywhere in tests

You're right, I had a too brief look, it gets mixed in via `ArbitraryInstances`. So if there was some equivalent derivation for Scala 3, it shouldn't be too hard to plug it in thanks to that trait, but no easy removal.

**Comment by bplommer** [comment]
> vulcan-generic, vulcan-enumeratum are not published

Vulcan-generic is coming soon (though without support for value classes, at least initially)

**Comment by catostrophe** [comment]
@ybasket Let's make a list of the repos to be migrated and mark those you're working on

**Comment by catostrophe** [comment]
I also can take some

**Comment by ybasket** [comment]
@catostrophe I was actually already planning to compile such list here later today. I linked all PRs to the core one, so should be easy to do (I'm on mobile right now, could only do later). No PRs in the making, choose any of the remaining. Avro and dependent aren't possible yet, `vulcan-generic` is still missing it seems…

**Comment by bplommer** [comment]
> Avro and dependent aren't possible yet, `vulcan-generic` is still missing it seems…

Yeah, I got massively side-tracked when learning Shapeless 3. I think it should be pretty straightforward to replace the derived codecs with hand-written ones though - happy to give it a go.

**Comment by catostrophe** [comment]
Here's the list:
 - trace4cats-avro
 - trace4cats-avro-kafka
 - trace4cats-components
 - trace4cats-dynamic-extras
 - trace4cats-kafka
 - trace4cats-opentelemetry
 - trace4cats-tail-sampling-extras
 - trace4cats-zio

I've taken opentelemetry.

**Comment by catostrophe** [comment]
I tried to cross-build the `opentelemetry` repo and it turned out the protobuf/json model is heavily dependent from circe-generic-extras transformation. We need another way of derivation for configured codecs.

**Comment by ybasket** [comment]
`circe-core` has a fresh PR that adds some `Configuration` support on Scala 3: https://github.com/circe/circe/pull/1800

It's neither merged nor released yet and also not a drop-in for `circe-generic-extras`, but yet could help trace4cats at one point.

**Comment by catostrophe** [comment]
@bplommer any ETA for `vulcan-generic` on Scala 3? Days or weeks?

**Comment by bplommer** [comment]
@catostrophe I'll try to find the time this weekend, but can't promise anything.

I would suggest using manual derivation anyway though, as the Scala 3 version generally won't produce the same Avro schemas as the Scala 2 version for coproduct types - this is because Scala 3 will use Shapeless 3, which orders subtypes by order they are declared, whereas Scala 2 uses Magnolia, which orders them alphabetically. This would prevent interop between the Scala 2 and Scala 3 versions, given that the readers don't seem to be doing [schema resolution](https://avro.apache.org/docs/current/spec.html#Schema+Resolution) against the writers.

**Comment by catostrophe** [comment]
@bplommer I wrote them manually to reproduce the output put from the current generic impl.

**Comment by catostrophe** [comment]
Congrats! Just released all repositories under v0.12.0 with Scala 3 support (except for `components`).
