### ISSUE TITLE
Break up project

### ISSUE THREAD

**Issue by janstenpickle** [trace4cats/trace4cats#551]
Trace4cats project has become very large. Builds are taking a long time and non-core dependencies are sometimes delaying the release of new versions (e.g. CE3/Tapir).

I propose creating a new organisation and the following repositories (I think I've covered everything, if it's not listed below it's probably captured by the core repo):

- `trace4cats`
	- core libraries and interfaces
- `trace4cats-zio`
	- Zio implementations of core interfaces
- `natchez`
	- Conversion to/from Natchez traces
- `trace-http4s`
	- trace context injectors for http4s interfaces
- `trace-sttp`
	- context injectors for sttp/Tapir interfaces
- `trace-kafka`
	- context injectors for Kafka clients
- `http-exporter`
	- common code for constructing http based exporters
- `avro`
	- Avro exporters; TCP, UDP and Kafka. (We may want an `avro-kafka` module, just to further separate concerns)
- `opentelemetry`
	- Open Telemetry export implementations
- `jaeger`
	- Jaeger export implmentations
- `stackdriver` (Maybe rename to `google-cloud-trace`)
	- Stackdriver export implmentations
- `datadog`
	- Datadog exporter
- `newrelic`
	- NewRelic exporteer
- `zipkin`
	- Zipkin exporter
- `tail-sampling`
	- Tail sampling interfaces & implementations
- `components`
	- the collectors and agents
- `docs`
	- Documentation and examples

Obviosuly this makes ongoing management a bit more difficult, but hopefully scalasteward, depandabot and mergify will help there.

The only question is timing, I think we should maybe aim to do this prior to full Scala 3 migration so that lagging dependencies can be updated as they become available.

A good first step may be to separate out the `components` repo so the build is separated and #515 fixed.

**Comment by catostrophe** [comment]
Great idea. I think every repo name in the new org should be prefixed with `trace4cats-` (as well as maven artifacts). The most difficult thing is to do the migration at one time.

**Comment by catostrophe** [comment]
The original repo can be moved to the org.
Then we can cut modules from it one by one.

**Comment by catostrophe** [comment]
At the same time, it's a huge burden on maintainers to release a project with like 17 repos.

**Comment by janstenpickle** [comment]
> The original repo can be moved to the org.
> Then we can cut modules from it one by one.

Yes, that's what I thought we'd do as a starting point, then move straight onto migrating the docker images.

> At the same time, it's a huge burden on maintainers to release a project with like 17 repos.

Yeah, this is what concerns me and why I had previously been more in favour of a single repo. I think the scales have just tipped in favour of breakthing things up now though with the CE3 migration pain. Maybe just not as granular as I've suggested.

I think it may be nice if we create a `g8` template for people to create new exporters too, maybe that will help shift some of the maintenance burden - people can just create and maintain their own exporters without feeling the need to contribute back to a central repo.

**Comment by janstenpickle** [comment]
Another motivation for this is the inclusion of ZIO on the core repo. I would like this project to more closely align with the Typelevel community and, given the history between ZIO's community leader and Typelevel, I believe the direct inclusion of ZIO somewhat stands in the way of that goal.

**Comment by catostrophe** [comment]
Done
