### ISSUE TITLE
Traced logging?

### ISSUE THREAD

**Issue by jarrodcodes** [trace4cats/trace4cats#616]
Hi there! This library is awesome, and I really enjoy using it. One thing that is missing is a traced logger, similar to the one in natchez-extras [(TracedLogger),](https://github.com/ovotech/natchez-extras/blob/master/natchez-extras-log4cats/src/main/scala/com/ovoenergy/natchez/extras/log4cats/TracedLogger.scala) where the current trace context is added to logs as mdc keys. I was curious if the maintainers would be interested in this functionality, and if so, I'd be happy to submit a PR. Thanks!

**Comment by catostrophe** [comment]
IMO, logging via MDC is conceptually broken, because it uses `ThreadLocal`s under the hood. I've never used `log4cats` with MDC and I'm not sure how it pushes the context down to `slf4j`. I will be grateful for a link that shows how they make working with MDC safe with fibers.

Logging libraries I use in prod -- ([tofu-logging](https://docs.tofu.tf/docs/logging) and [logstage](https://izumi.7mind.io/logstage/) -- both support contexts. And adding trace info to the log context is done in a few lines of code, so I've never thought about publishing it :)

**Comment by catostrophe** [comment]
Hey @ChristopherDavenport!
Could you elaborate on how you make MDC fiber-safe in the log4cats-slf4j bridge?

**Comment by janstenpickle** [comment]
I know that https://github.com/valskalla/odin is able to support it as well. I'm piloting it at work at the moment and depending on how that goes be releasing an interop library.

In the meantime, did you know we have an [interop library between Trace4Cats and Natchez](https://github.com/trace4cats/trace4cats-docs/blob/master/docs/examples.md#natchez) that will allow you to use the `TracedLogger`?

**Comment by ChristopherDavenport** [comment]
Hey @catostrophe  So the reason is this is safe is that this takes complete control of the threadlocal within one atomic block on the thread. Since this is an uninterruptible atomic unit this safe to do in this fashion.

https://github.com/typelevel/log4cats/blob/main/slf4j/src/main/scala/org/typelevel/log4cats/slf4j/internal/Slf4jLoggerInternal.scala#L43-L53

**Comment by jarrodcodes** [comment]
Thank you all for your responses. I have tried Odin for logging in a spike that is going well and I think we will most likely switch over to using it. However, this then changes the nature of my request, because we want Odin logs to have the same DataDog TraceId as the trace4cats traces. Currently, the only way to do this is to custom map the TraceId with the same logic as is in DataDogSpan. I would much rather have this be a public method for `TraceContext => Any` so that this can be referenced without custom code. I propose exposing this as a new model called "ExternalTraceContext" or similar that DataDogSpan extends. Or we could simply add the following to object DataDogSpan:

 `def toTraceId(spanContext: SpanContext): BigInt = BigInt(1, spanContext.traceId.value.drop(8))
  def toSpanId(spanContext: SpanContext): BigInt = BigInt(1, spanContext.spanId.value)`

This way the TraceId will programmatically match for both the logs and the spans sent to DataDog.

Thank you all for your time

**Comment by jarrodcodes** [comment]
I went ahead and made PRs that would solve this issue:
https://github.com/trace4cats/trace4cats/pull/622
https://github.com/trace4cats/trace4cats-datadog/pull/35

**Comment by janstenpickle** [comment]
@jarrodcodes thanks for the contributions! On the face of it I prefer option 2 as it requires no changes to core, could you explain a bit more the motivation behind `ExternalTraceContext`?

**Comment by jarrodcodes** [comment]
Sure. The main benefit of `ExternalTraceContext` is that any external service that TraceIds, SpanIds, and ParentIds could be shipped to, the methods of calculating these ids will be available for any other code that wants to programmatically match them. For example: In my logging context, I have a Span that will be sent to DataDog, using `DataDogSpan`. However, the method of calculating the TraceId that will be sent to Datadog is currently private and internal: `(val traceId = new BigInteger(1, span.context.traceId.value.drop(8))`. So if I want to programmatically match this TraceId in another context, such as logging, I currently have to copy over that id calculation method and hope that it doesn't change and break. 

For example: In my logger with tracing context:

  `implicit private def traceContext[F[_]: Sync]: WithContext[Kleisli[F, Span[F], *]] =
    new WithContext[Kleisli[F, Span[F], *]] {
      override def context: Kleisli[F, Span[F], Map[String, String]] =
        Kleisli { span =>
          val traceId: String = BigInt(1, span.context.traceId.value.drop(8)).toString
          val spanId: String = BigInt(1, span.context.spanId.value).toString
          Map("dd.trace_id" -> traceId, "dd.span_id" -> spanId).pure[F]
        }
    }`

would become:

`  implicit private def traceContext[F[_]: Sync]: WithContext[Kleisli[F, Span[F], *]] =
    new WithContext[Kleisli[F, Span[F], *]] {
      override def context: Kleisli[F, Span[F], Map[String, String]] =
        Kleisli { span =>
          val traceId: String = DataDogSpan.traceId(span.context).toString
          val spanId: String = DataDogSpan.spanId(span.context).toString
          Map("dd.trace_id" -> traceId, "dd.span_id" -> spanId).pure[F]
        }
    }`

This trait would also be inherited by any future external tracing services supported by trace4cats, so I placed the model in core so that it would be available for new modules instead of just DataDog.

**Comment by jarrodcodes** [comment]
Checking in, hopefully my response was helpful?
