### ISSUE TITLE
Bug: Duplicate span IDs

### ISSUE THREAD

**Issue by ybasket** [trace4cats/trace4cats#740]
When testing #729 with my [demo repo](https://github.com/ybasket/trace4cats-iolocal-demo), I encountered many duplicate span IDs within a trace. It seems as #732 introduced a regression here when switching to `cats.effect.std.Random` – the instance acquired via `Random.javaUtilConcurrentThreadLocalRandom` seems to start with the same seed (which can't be changed) for each of CE's worker threads, resulting in similar span ID sequences being produced. This isn't well-documented, but quite visible in tests (maybe one should be added to trace4cats to check for this?). If one provides a `Random` instance backed another RNG implementation in implicit scope, the problem vanishes. Probably affects trace ID generation as well.

One can test the problem with this simple app:

```scala
import cats.effect._
import cats.effect.std.Random
import cats.syntax.all._
import io.janstenpickle.trace4cats.model.SpanId

object Randoms extends IOApp.Simple {
  override def run: IO[Unit] = (spans, spans, spans, spans).parMapN { (b1, b2, b3, b4) =>
    IO.println((b1, b2, b3, b4))
  }.flatten

  val spans = SpanId.gen[IO].replicateA(8)

  val bytesTL = IO(Random.javaUtilConcurrentThreadLocalRandom[IO].nextBytes(8).map(SpanId.unsafe).replicateA(8)).flatten
  val bytesSR = Random.scalaUtilRandom[IO].flatMap(_.nextBytes(8).map(SpanId.unsafe).replicateA(8))
  val bytesSRN = Random.scalaUtilRandomN[IO](8).flatMap(_.nextBytes(8).map(SpanId.unsafe).replicateA(8))
}
```

It'll print something like
```scala
(List(5332f38d1b42bce2, 5332f38d1b42bce2, 5332f38d1b42bce2, 5332f38d1b42bce2, 5332f38d1b42bce2, 5332f38d1b42bce2, 5332f38d1b42bce2, 5332f38d1b42bce2),List(24329fc1655fc619, 24329fc1655fc619, 24329fc1655fc619, 24329fc1655fc619, 24329fc1655fc619, 24329fc1655fc619, 24329fc1655fc619, 24329fc1655fc619),List(9880c7fbd03a316e, 9880c7fbd03a316e, 9880c7fbd03a316e, 9880c7fbd03a316e, 9880c7fbd03a316e, 9880c7fbd03a316e, 9880c7fbd03a316e, 9880c7fbd03a316e),List(1bb4e609932ac0a5, 1bb4e609932ac0a5, 1bb4e609932ac0a5, 1bb4e609932ac0a5, 1bb4e609932ac0a5, 1bb4e609932ac0a5, 1bb4e609932ac0a5, 1bb4e609932ac0a5))
```

By replacing `spans` with one of the `bytesXYZ`, you can see the behaviours of different RNGs.

Unfortunately, the issue isn't super-easy to fix because all `Random` constructors except `javaUtilConcurrentThreadLocalRandom` are effectful, so either the user needs to always provide a `Random` instance (`scalaUtilRandomN`), the instance is created via `SyncIO` and then `mapK`ed (a hack) or `cats.effect.std.Random` is removed from the `Gen` traits (effectively partially reverting #732).

@catostrophe

**Comment by catostrophe** [comment]
@ybasket Could you clarify, do you think the culprit is #732 not #736? I think the behaviour didn't change in #732.

**Comment by ybasket** [comment]
> @ybasket Could you clarify, do you think the culprit is #732 not #736? I think the behaviour didn't change in #732.

You're right, #736 is the one I meant, I just linked the wrong PR.

**Comment by catostrophe** [comment]
Ok. Working on a fix.

**Comment by catostrophe** [comment]
I think it's a bug in CE3:
https://github.com/typelevel/cats-effect/blob/0a6bae21333e96c227eb031e6db777aa1c8d0197/std/shared/src/main/scala/cats/effect/std/Random.scala#L530-L533

A reference to the same array leaks and returns every time when `nextBytes` is replicated. When we create a span, we don't make a copy of the array and use the reference as is.

**Comment by catostrophe** [comment]
@ybasket see https://github.com/typelevel/cats-effect/pull/2972

**Comment by catostrophe** [comment]
I think we shouldn't revert anything in trace4cats and should just wait for a patch release in CE3.

**Comment by ybasket** [comment]
> I think we shouldn't revert anything in trace4cats and should just wait for a patch release in CE3.

Agree, once it's released (and CE is usually quite quick on that), the thread local implementation is the nicest for trace4cats.

Nice work!

**Comment by catostrophe** [comment]
@ybasket @janstenpickle Should we make and use a copy of the array passed to `TraceId.apply`? It would protect us from such a leak, if we did it.

**Comment by janstenpickle** [comment]
Yes, I think that's probably a good idea, just in case there's a regression to your fix in cats-effect.

**Comment by ybasket** [comment]
I'm slightly leaning towards not defensively copying as it protects only against a very specific bug that's unlikely to ever come up again – unless you want to publish a trace4cats release without waiting for CE. Instead of imposing runtime cost everywhere, we could add a test based on the reproducer snippet I posted above, just checking that a small set of span IDs that's generated by the default `SpanId.Gen` (or `TraceId.Gen`) are distinct. Would false positive once in a lifetime, but cover more potential bugs than the array copying. Just my 2 cents though.

**Comment by Nurlan-Mammadli** [comment]
Hello All,

First of all, thank you for this great library.

I also had a similar problem with duplicate Span/Trace IDs. I just checked it with the new version of CE, and it worked as expected 🎉

I guess you can merge it now and publish a new version of your library (which I'm waiting for a couple of days now) 🙂

**Comment by janstenpickle** [comment]
Thanks @Nurlan-Mammadli, there is an associated branch in review to ensure we don't have a regression in the future, so will wait for that to merge before closing this.
