### ISSUE TITLE
Reworked package structure

### ISSUE THREAD

**Issue by janstenpickle** [trace4cats/trace4cats#744]
Follows from #701. Let's discuss a new package name and structure.

- As suggested previously, we should probably go with `trace4cats` as the root package
- We'll need to provide Scalafix migrations for ScalaSteward - I've not done this before, so any help would be appreciated!
- As part of #701 and #742 some libraries will no longer be published (`inject` probably being the most used), we'll need to leave deprecated versions of interfaces to redirect to the new libraries and packages

Let's discuss!

**Comment by janstenpickle** [comment]
(Will use this to track discussion)

### Kernel module

`ToHeaders` and assocateded code -> `trace4cats.kernel.headers`
`SpanCompleter, SpanExporter, SpanSampler` -> `trace4cats.kernel.export`
`*Attributes` -> `trace4cats.kernel.attributes`

(Maybe we should just have `trace4cats` instead of `trace4cats.kernel`?)

### Core module

`LogSpanCompleter, LogSpanExporter` -> `trace4cats.export.log`
`inject.*` -> ???
`rate.*` -> ???

**Comment by bplommer** [comment]
> (Maybe we should just have trace4cats instead of trace4cats.kernel?)

👍 cats and cats-effect have kernel stuff in a kernel package but aliased to the root package - not sure why but might be worth looking into the reasoning

**Comment by bplommer** [comment]
`trace4cats.base.context` -> `trace4cats.mtl`?

**Comment by janstenpickle** [comment]
> `trace4cats.base.context` -> `trace4cats.mtl`?

Maybe just `trace4cats.context` as it's not a full MTL, it just deals with contextual effects

**Comment by janstenpickle** [comment]
> 👍 cats and cats-effect have kernel stuff in a kernel package but aliased to the root package - not sure why but might be worth looking into the reasoning

So I've found out why this is; they want to keep the kernel code in its own package and library, but also enable app developers to import `cats.effect._` and have everything they need. I quite like that approach as it will allow us to organise code a nice package structure, while supporting a wildcard import.

**Comment by catostrophe** [comment]
Wow
https://github.com/scala-steward-org/scala-steward/issues/2327

**Comment by catostrophe** [comment]
We'll have to add rewrite rules to
https://github.com/scala-steward-org/scala-steward/blob/main/modules/core/src/main/resources/scalafix-migrations.conf

**Comment by janstenpickle** [comment]
> We'll have to add rewrite rules to [https://github.com/scala-steward-org/scala-steward/blob/main/modules/core/src/main/resources/scalafix-migrations.conf](https://github.com/scala-steward-org/scala-steward/blob/main/modules/core/src/main/resources/scalafix-migrations.conf?rgh-link-date=2022-04-30T07%3A13%3A10Z)

Yep, will have to do the same for the new modules too. Shall we change the organization for Maven central as part of this?

**Comment by catostrophe** [comment]
I think, yes.

**Comment by janstenpickle** [comment]
Tracking PRs on other repos here:

https://github.com/trace4cats/trace4cats-http4s/pull/111
https://github.com/trace4cats/trace4cats-natchez/pull/94
https://github.com/trace4cats/trace4cats-kafka/pull/96
https://github.com/trace4cats/trace4cats-tail-sampling-extras/pull/121
https://github.com/trace4cats/trace4cats-avro/pull/128
https://github.com/trace4cats/trace4cats-dynamic-extras/pull/108

**Comment by catostrophe** [comment]
https://github.com/typelevel/catbird/releases/tag/v22.4.0

See scalafix example here

**Comment by janstenpickle** [comment]
I've had to somewhat bruteforce the scalafix, but it seems to work https://github.com/trace4cats/trace4cats/pull/774

**Comment by janstenpickle** [comment]
@bplommer @catostrophe I think everything has been migrated to the new package structure. It should be much easier to work with a `trace4cats._` import now.

Now that the public ScalaSteward instance is back up, I think next week would be a good time to get the release train going. 

I've created a [new issue for releasing `0.14.0`](https://github.com/trace4cats/trace4cats/issues/775), please let me know there if I've missed anything.

Thanks!

**Comment by janstenpickle** [comment]
OK, this is now released!
