### ISSUE TITLE
`Trace` implementations written directly against `Kleisli` and `IOLocal`

### ISSUE THREAD

**Issue by bplommer** [trace4cats/trace4cats#745]
Having everything implemented against the contextual abstractions is elegant conceputally, but it also creates an obstacle to understanding the library (you need to internalise the abstractions and/or follow extra indirection) - providing specific concrete implementations would make it easier to understand the library in terms of concrete behaviour, while also providing an on-ramp for understanding the more abstract implementation.

**Comment by janstenpickle** [comment]
Is [this](https://github.com/trace4cats/trace4cats/blob/master/modules/inject/src/main/scala/io/janstenpickle/trace4cats/inject/Trace.scala#L87-L141=) what you mean? The instances built from the contextual utils are there so people can use them if they wish, but we do provide concrete implementations of `Trace` as well.

**Comment by bplommer** [comment]
Uhh... yes, yes it is. Not sure what I was thinking here 🤦
